name: api_module
description: Modulo para manejar las consultas hacia servicios REST
version: 0.0.1
homepage: https://www.anibalmunoz.com/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter: null
